---
title: "První nález *Euoniticellus fulvus* (Coleoptera: Scarabaeidae) v západních Čechách po půl století"
author: "Jonáš Gaigr"
date: "`r format(Sys.Date(), '%d. %m. %Y')`"
output:
  word_document:
    toc: false
    number_sections: false
bibliography: references.bib
csl: czech_faunistic_author_year.csl
lang: cs
---

**Adresa autora:**  
Agentura ochrany přírody a krajiny ČR, Kaplanova 1931/1, 148 00 Praha 1  
<jonas.gaigr@gmail.com>

---

# Abstrakt

*Euoniticellus fulvus* Goeze, 1777 is recorded after 57 years from western Bohemia from Horšovský Týn: CZ – Bohemia occ., Horšov, 5 km jižně (6443c), 49°32'32.043"N, 12°54'38.946"E, alluvium of the Plešský stream, PP (Nature Monument) Veský Mlýn, 380 m a.s.l., 8.VII.2025, 1 spec., J. Gaigr leg., det. et coll. The examined specimen was collected in horse dung, on a dirt road.

**Key words:** Coleoptera, Scarabaeidae, *Euoniticellus fulvus*, faunistic record, Czech Republic, western Bohemia

---

# Text

*Euoniticellus fulvus* Goeze, 1777. Bohemia occ., Horšov, 5 km jižně (6443), 49°32'32.043"N, 12°54'38.946"E, koňský trus na cestě, Horšovská obora, 380 m n.m., 8.VII.2025, 1 ex., J. Gaigr leg. et det. et coll. Lokalita se nachází asi dva kilometry severozápadně od Horšovského Týna a jde o bývalou oboru o rozloze asi 400 hektarů pokrytou mozaikou trvalých lesních porostů, zemědělské půdy, rybníků a lesů (Obr. 1). Druh byl nalezen v koňském trusu, společně s *Aphodius (Colobopterus) erraticus* (Linnaeus, 1758), *Aphodius (Eupleurus) subterraneus* (Linnaeus, 1758) a *Onthophagus coenobita*, při náhodném sběru na cestě v lipové aleji. Okolí šotolinové cesty na lokalitě tvoří trvalý travní porost a zemědělská půda. Nejbližší aktivně využívaná koňská pastvina se nachází přibližně 500 m od místa nálezu.

Skvrnař žlutý (*Euoniticellus fulvus*) (Goeze, 1777) je drobný zástupce vrubounovitých brouků (Scarabaeidae), podčeledi Scarabaeinae, tribu Oniticellini. Dospělci měří 8–11 mm, tělo je štíhlé, mírně klenuté, se světle žlutohnědými až plavými krovkami a tmavší hlavou a štítem (Obr. 2). Na povrchu krovek je jemná, podélná rýhovitost, typická pro rod *Euoniticellus*. Samci mají na hlavě nízký štítkovitý výběžek. Nomenklatoricky byl druh původně popsán Goezem v roce 1777. V minulosti býval řazen také do rodů *Oniticellus* nebo *Copris*, současné taxonomické pojetí stabilně užívá rod *Euoniticellus* [@gbif2023]. Areál rozšíření zahrnuje velkou část Palearktu od jižní Evropy po Střední Asii, zasahuje do severní Afriky a na Blízký východ. Druh byl cíleně zavlečen a etablován také mimo původní areál v Austrálii, kde byl úspěšně introdukován v rámci biologického programu pro rozklad trusu hospodářských zvířat.

V Česku je vázán na teplé otevřené pastviny, kde se vyvíjí v trusu velkých savců, převážně koní a skotu. Tesař [@tesar1957] druh v Čechách uvádí z okolí Prahy a Radotína, na Moravě z Čejče a dalších lokalit. V posledním Červeném seznamu hodnocen jako zranitelný [@hejda2017]. Na přelomu tisíciletí byl známý výskyt pouze na jižní Moravě [@chybik2005]. V Čechách byl druh považován za vymizelý [@jurena2008]. V posledních dvou desetiletích však druh zjevně expanduje (Obr. 3). Peřinková a Fischer [@perinkova2010] popisují šířní druhu do středních poloh na jihozápadní Moravě. *E. fulvus* se již rozšířil v nižších polohách východních Čech [@mertlik2019; @mertlik2020], byl opět potvrzen na území Prahy [@sommer2024] a Českého krasu [@kostir2024]. Nalezen byl i na Šumavě v nadmořské výšce 800 m. n. m. [@ambrozova2021]. Historické údaje z území západních Čech byly publikovány z Františkových Lázní, Stříbra a Horažďovic [@jurena2008]. Z území Plzeňského a Karlovarského kraje nebyl výskyt druhu v posledních desetiletích publikován [@tyr2021soupis]. Podobný trend šíření byl zaznamenán i v sousedním Německu [@iNaturalist2025]. Výše uvedený nález představuje první publikovaný doklad výskytu druhu na území Plzeňského a Karlovarského kraje po 56 letech.

---

# Poděkování

Děkuji K. Chobotovi (AOPK ČR, Praha) za revizi determinace ostatních druhů ve sběru.

---

# Přílohy

Obr. 1. Území bývalé Horšovské obory. Foto: J. Gaigr  
Fig. 1.

Obr. 2. *Euoniticellus fulvus* Goeze, 1777 z lokality Horšov. Foto: J. Gaigr  
Fig. 2. 

Obr. 3. Rozříření *Euoniticellus fulvus* Goeze, 1777 v Česku;  Publikované údaje podle  
Fig. 3.

---

# Literatura




